name: CI/CD Pipeline for Roman Converter

on:
  push:
    branches:
      - main   # Cambia a 'master' si tu rama principal se llama 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm init -y
        npm install mocha chai eslint --save-dev

    - name: Run Mocha tests
      run: |
        npx mocha test.html --reporter spec
      continue-on-error: false

    - name: Run ESLint
      run: |
        npx eslint script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
